
export const TOP_50_COINS: string[] = [
  'BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT', 'XRPUSDT', 'DOGEUSDT', 'ADAUSDT', 'AVAXUSDT', 'SHIBUSDT', 'DOTUSDT',
  'LINKUSDT', 'TRXUSDT', 'MATICUSDT', 'LTCUSDT', 'BCHUSDT', 'ICPUSDT', 'NEARUSDT', 'UNIUSDT', 'FILUSDT', 'APTUSDT',
  'INJUSDT', 'ETCUSDT', 'IMXUSDT', 'HBARUSDT', 'ATOMUSDT', 'TIAUSDT', 'STXUSDT', 'RNDRUSDT', 'OPUSDT', 'MKRUSDT',
  'GRTUSDT', 'LDOUSDT', 'VETUSDT', 'SEIUSDT', 'SUIUSDT', 'ARBUSDT', 'AAVEUSDT', 'ALGOUSDT', 'FETUSDT', 'RUNEUSDT',
  'EGLDUSDT', 'TAOUSDT', 'THETAUSDT', 'FLOWUSDT', 'MANAUSDT', 'SANDUSDT', 'AXSUSDT', 'FTMUSDT', 'GALAUSDT', 'PEPEUSDT'
];
